### ISSUE TITLE
Node 10.x support

### ISSUE THREAD

**Issue by cbratschi** [seangarner/node-stream-mmmagic#13]
mmmagic 0.5.1 contains a fix for Node 10.x. Please increase the version to 0.5.1.

**Comment by seangarner** [comment]
fixed in 23e86ad and 2.1.0 just released.  Thanks for the prod @cbratschi I'd missed the original PR notification.

**Comment by cbratschi** [comment]
@seangarner 0.5.1 includes the Node 10.x fix. The PR uses the older 0.5.0 build.

**Comment by seangarner** [comment]
@cbratschi `^0.5.0` will still install `0.5.1` assuming that you don't have a dep of `mmmagic` in your project fixed at an older version (which wouldn't make sense as it wouldn't work).  https://travis-ci.org/seangarner/node-stream-mmmagic/jobs/430462252 or `npm ls` it after installing to confirm:
```
npm ls
/home/sgarner/tmp-test
└─┬ stream-mmmagic@2.1.0
  ├── buffer-peek-stream@1.0.1
  └─┬ mmmagic@0.5.1
    └── nan@2.11.0
```

Feel free to ping me if you need it _fixed_ to `0.5.1`.

**Comment by cbratschi** [comment]
@seangarner Yes, that's correct. Thanks for the quick solution.
