### ISSUE TITLE
New Magic object is created on every call

### ISSUE THREAD

**Issue by freitagbr** [seangarner/node-stream-mmmagic#7]
Every time `streamMmmagic` is called, a new `Magic` object is created. Only one `Magic` object is needed for the `detect` method, which can be used any number of times. Therefore, a single `Magic` object should be created on initialization. If the user specifies a `magicFile`, however, a new instance needs to be created.

**Comment by seangarner** [comment]
Interesting suggestion.  Unfortunately `magicFile` could be changed globally (see explanation #5).

I guess I could keep a cache of them.  That assumes nobody would use a large number of magic files though.  Or perhaps watch for changes to the global one and reset the cache.

@freitagbr does your use case create that many streams that means that the instantiation of `Magic` is expensive?

**Comment by freitagbr** [comment]
In my use case, I am receiving files that are going to be some sort of compressed archive, like a .tgz, .tbz2, .tar, .zip, etc., and those archives may contain other archives. I am using this module to detect the mimetype of the archive so it can be handled correctly, so the function ends up getting called a lot.

I have a branch to fix this, and I also implemented caching for other `Magic` objects if the `magicFile` is changed. I'm assuming it's not common to use a large number of magic files, so it is probably fine to cache a few `Magic` objects this way.

**Comment by seangarner** [comment]
I'm tempted to remove the global config and do a semver major release.  Do you use the global config, or do you typically pass in options each time?

If you've already got a branch then feel free to PR.

**Comment by freitagbr** [comment]
I don't use either typically, though I would prefer to pass in the options each time.

Another option would be to subclass `Magic` and provide something like a `detectStream` method. This way, `Magic` objects can be created as necessary. However, I like being able to require-and-go with this module.

**Comment by seangarner** [comment]
@freitagbr I've just published `2.0.0-pre.0`.  As well as removing the module level config for magic file and adding it as a call time option, it adds the ability to control how many bytes are buffered and sent to libmagic.  I've reduced the default down to 1K which is plenty for filetype, and for my use case works for encoding too.  See the updated readme for more info.

Once I've done some more thorough testing I'll publish a final 2.0.0 in a few days.

**Comment by freitagbr** [comment]
Awesome, thank you @seangarner! Configuring the buffer size was going to be my next suggestion but you beat me to it.

**Comment by seangarner** [comment]
@freitagbr the 1K size didn't work well for me during testing so I've reverted it to 16K as with v1.  But it's configurable in 2.0.0, so you'll be able to reduce for your needs.  FWIW 256 bytes seems about as low as you want to take it for reliable file type detection.

I've just released 2.0.0.
